#############################################################################
# Licensed Materials - Property of HCL*
# (C) Copyright HCL Technologies Ltd. 2017, 2019 All rights reserved.
# * Trademark of HCL Technologies Limited
#############################################################################

version: "2"
services:
  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    networks:
      - wa-net
#    environment:
#      - NODE_ENV=production
    volumes:
      - ./app/:/home/node/app
#    expose:
#      - "8081"
#    command: "npm start"
    command: "bash"

